//! Model metadata structures — TOML ↔ Rust.

use serde::{Deserialize, Serialize};

/// A single built-in model entry, deserialized from `data/catalog/models/*.toml`.
///
/// Matches the shape of `model_db::ModelEntry` but uses owned `String` types
/// because it comes from a runtime-parsed TOML rather than static literals.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BuiltinModelEntry {
    /// Model identifier (e.g., "claude-sonnet-4-20250514")
    pub id: String,
    /// Human-readable model name (e.g., "Claude Sonnet 4")
    pub name: String,
    /// API protocol to use
    pub api: String,
    /// Provider name (e.g., "anthropic", "openai")
    pub provider: String,
    /// Whether this model supports reasoning/thinking
    #[serde(default)]
    pub reasoning: bool,
    /// Supported input modalities
    #[serde(default)]
    pub input: Vec<String>,
    /// Cost per million input tokens (USD)
    #[serde(default)]
    pub cost_input: f64,
    /// Cost per million output tokens (USD)
    #[serde(default)]
    pub cost_output: f64,
    /// Cost per million cached read tokens (USD)
    #[serde(default)]
    pub cost_cache_read: f64,
    /// Cost per million cached write tokens (USD)
    #[serde(default)]
    pub cost_cache_write: f64,
    /// Maximum context window in tokens
    #[serde(default)]
    pub context_window: u32,
    /// Maximum output tokens
    #[serde(default)]
    pub max_tokens: u32,
}

impl BuiltinModelEntry {
    /// Check if this model supports image/vision input.
    pub fn supports_vision(&self) -> bool {
        self.input.iter().any(|m| m == "image" || m == "Image")
    }

    /// Check if this model supports reasoning/thinking.
    pub fn supports_reasoning(&self) -> bool {
        self.reasoning
    }

    /// Calculate the cost for a given token usage.
    pub fn calculate_cost(
        &self,
        input_tokens: u64,
        output_tokens: u64,
        cache_read: u64,
        cache_write: u64,
    ) -> f64 {
        let in_cost = (input_tokens as f64 / 1_000_000.0) * self.cost_input;
        let out_cost = (output_tokens as f64 / 1_000_000.0) * self.cost_output;
        let cr_cost = (cache_read as f64 / 1_000_000.0) * self.cost_cache_read;
        let cw_cost = (cache_write as f64 / 1_000_000.0) * self.cost_cache_write;
        in_cost + out_cost + cr_cost + cw_cost
    }
}

/// Load all built-in models from the bundled TOML files.
pub fn load_builtin_models() -> &'static std::collections::BTreeMap<String, Vec<BuiltinModelEntry>> {
    &crate::catalog::CatalogRoot::get().models
}

/// Number of built-in models (across all providers).
pub fn builtin_model_count() -> usize {
    load_builtin_models().values().map(|v| v.len()).sum()
}

/// Index of all built-in model TOML files.
///
/// Each file in `data/catalog/models/*.toml` is `include_str!`-ed at compile
/// time and returned as a `(provider_id, toml_str)` tuple. The full list is
/// generated by the build script `build.rs` (see there for the enumeration
/// logic). For now, we maintain a hand-rolled macro of `include_str!` calls
/// that mirrors the directory contents; a future `build.rs` will generate this.
///
/// When a new TOML file is added:
///   1. Place it at `data/catalog/models/<provider>.toml`
///   2. Add a `include_str!(...)` line below in alphabetical order
///   3. Run `cargo build -p oxi-ai` to verify
pub fn models_index() -> &'static [(&'static str, &'static str)] {
    &[
        ("amazon-bedrock", include_str!("../../data/catalog/models/amazon-bedrock.toml")),
        ("anthropic", include_str!("../../data/catalog/models/anthropic.toml")),
        ("azure-openai-responses", include_str!("../../data/catalog/models/azure-openai-responses.toml")),
        ("cerebras", include_str!("../../data/catalog/models/cerebras.toml")),
        ("cloudflare-ai-gateway", include_str!("../../data/catalog/models/cloudflare-ai-gateway.toml")),
        ("cloudflare-workers-ai", include_str!("../../data/catalog/models/cloudflare-workers-ai.toml")),
        ("deepseek", include_str!("../../data/catalog/models/deepseek.toml")),
        ("fireworks", include_str!("../../data/catalog/models/fireworks.toml")),
        ("github-copilot", include_str!("../../data/catalog/models/github-copilot.toml")),
        ("google-vertex", include_str!("../../data/catalog/models/google-vertex.toml")),
        ("google", include_str!("../../data/catalog/models/google.toml")),
        ("groq", include_str!("../../data/catalog/models/groq.toml")),
        ("huggingface", include_str!("../../data/catalog/models/huggingface.toml")),
        ("kimi-coding", include_str!("../../data/catalog/models/kimi-coding.toml")),
        ("minimax-cn", include_str!("../../data/catalog/models/minimax-cn.toml")),
        ("minimax", include_str!("../../data/catalog/models/minimax.toml")),
        ("mistral", include_str!("../../data/catalog/models/mistral.toml")),
        ("moonshotai-cn", include_str!("../../data/catalog/models/moonshotai-cn.toml")),
        ("moonshotai", include_str!("../../data/catalog/models/moonshotai.toml")),
        ("openai-codex", include_str!("../../data/catalog/models/openai-codex.toml")),
        ("openai", include_str!("../../data/catalog/models/openai.toml")),
        ("opencode-go", include_str!("../../data/catalog/models/opencode-go.toml")),
        ("opencode", include_str!("../../data/catalog/models/opencode.toml")),
        ("openrouter", include_str!("../../data/catalog/models/openrouter.toml")),
        ("together", include_str!("../../data/catalog/models/together.toml")),
        ("vercel-ai-gateway", include_str!("../../data/catalog/models/vercel-ai-gateway.toml")),
        ("xai", include_str!("../../data/catalog/models/xai.toml")),
        ("xiaomi", include_str!("../../data/catalog/models/xiaomi.toml")),
        ("zai", include_str!("../../data/catalog/models/zai.toml")),
        ("byteplus", include_str!("../../data/catalog/openclaw/byteplus.toml")),
        ("chutes", include_str!("../../data/catalog/openclaw/chutes.toml")),
        ("deepinfra", include_str!("../../data/catalog/openclaw/deepinfra.toml")),
        ("gmi", include_str!("../../data/catalog/openclaw/gmi.toml")),
        ("kilocode", include_str!("../../data/catalog/openclaw/kilocode.toml")),
        ("moonshot", include_str!("../../data/catalog/openclaw/moonshot.toml")),
        ("novita", include_str!("../../data/catalog/openclaw/novita.toml")),
        ("nvidia", include_str!("../../data/catalog/openclaw/nvidia.toml")),
        ("ollama-cloud", include_str!("../../data/catalog/openclaw/ollama.toml")),
        ("qianfan", include_str!("../../data/catalog/openclaw/qianfan.toml")),
        ("qwen-oauth", include_str!("../../data/catalog/openclaw/qwen.toml")),
        ("stepfun", include_str!("../../data/catalog/openclaw/stepfun.toml")),
        ("venice", include_str!("../../data/catalog/openclaw/venice.toml")),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn models_index_loads_all_providers() {
        let idx = models_index();
        // We expect at least the 29 oxi-original providers.
        // (More may be added as openclaw/opencode imports land.)
        assert!(idx.len() >= 29, "got {} entries", idx.len());
        for (pid, body) in idx {
            assert!(!pid.is_empty(), "empty provider id");
            assert!(body.contains("provider ="), "{pid}: missing top-level provider field");
            assert!(body.contains("[[model]]"), "{pid}: missing model entries");
        }
    }

    #[test]
    fn all_loaded_models_round_trip() {
        // Each TOML file should be parseable and yield >=1 model.
        let root = crate::catalog::CatalogRoot::get();
        let total: usize = root.models.values().map(|v| v.len()).sum();
        assert!(total >= 900, "expected >= 900 models, got {total}");
    }
}
