[workspace]
resolver = "2"
members = ["oxi-ai", "oxi-agent", "oxi-tui", "oxi-cli", "oxi-sdk"]
exclude = ["scripts"]

[workspace.dependencies]
thiserror = "2"

[patch.crates-io]
oxi-ai = { path = "oxi-ai" }
oxi-agent = { path = "oxi-agent" }
oxi-sdk = { path = "oxi-sdk" }
oxi-tui = { path = "oxi-tui" }
oxi-cli = { path = "oxi-cli" }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
