//! Build script for oxi-ai.
//!
//! Previously auto-enumerated TOML model files under `data/catalog/models/`
//! and `data/catalog/openclaw/`. These are now replaced by the embedded
//! models.dev snapshot (`data/catalog/_snapshot.json.gz`).
//!
//! The snapshot is committed to the repo and included via `include_bytes!`
//! at compile time. No runtime IO is needed for the catalog.
//!
//! # CI / reproducible builds
//!
//! Set `OXI_CATALOG_SNAPSHOT=path` to inject a specific snapshot file
//! (e.g., from CI artifacts). Otherwise, the committed `_snapshot.json.gz`
//! is used by default from `include_bytes!` in `model_db.rs`.
//!
//! Model data © [models.dev](https://models.dev) (MIT).

use std::env;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let out_file = Path::new(&out_dir).join("catalog_index.rs");

    // Optional snapshot override (CI / release builds).
    // If OXI_CATALOG_SNAPSHOT is set, copy that file over the committed
    // snapshot so the `include_bytes!` below picks it up. This lets CI
    // inject a specific snapshot (e.g., from a fresh fetch) without
    // modifying the repo.
    if let Ok(custom_path) = env::var("OXI_CATALOG_SNAPSHOT") {
        let custom = Path::new(&custom_path);
        assert!(
            custom.exists(),
            "OXI_CATALOG_SNAPSHOT not found: {}",
            custom.display()
        );
        let committed = Path::new(&manifest_dir).join("data/catalog/_snapshot.json.gz");
        if custom.canonicalize().ok() != committed.canonicalize().ok() {
            std::fs::copy(custom, &committed)
                .unwrap_or_else(|e| panic!("failed to copy snapshot: {e}"));
            println!(
                "cargo:warning=OXI_CATALOG_SNAPSHOT applied: {}",
                custom.display()
            );
        }
        println!("cargo:rerun-if-env-changed=OXI_CATALOG_SNAPSHOT");
    }

    // Ensure the committed snapshot exists (it should — it's checked into git).
    let committed = Path::new(&manifest_dir).join("data/catalog/_snapshot.json.gz");
    assert!(
        committed.exists(),
        "Committed snapshot not found at {}. Run `gzip -c < api.json > data/catalog/_snapshot.json.gz`.",
        committed.display()
    );

    // Write a minimal index (previously auto-generated from TOML files).
    // The model_db materialize path reads the snapshot directly via include_bytes!.
    // This file is kept for backward compatibility (catalog_index.rs is included
    // by model.rs::models_index() but is no longer the primary data source).
    let body = "// AUTO-GENERATED by build.rs. DO NOT EDIT.\n\
                // Models are now loaded from the embedded models.dev snapshot.\n\
                &[]\n";
    std::fs::write(&out_file, body).expect("write OUT_DIR/catalog_index.rs");

    println!("cargo:rerun-if-changed=data/catalog/_snapshot.json.gz");
    println!("cargo:rerun-if-changed=build.rs");
}
