//! Build script: auto-enumerate catalog TOML files.
//!
//! For each file `data/catalog/models/<provider>.toml`, generates an
//! `include_str!` call in `OUT_DIR/catalog_index.rs`. The library
//! `include!`s that file once at compile time, so adding a new TOML file
//! to `data/catalog/models/` requires NO Rust code changes — the build
//! picks it up automatically.
//!
//! ## Layout
//!
//! ```text
//! data/catalog/
//!   providers.toml             # provider metadata (1 file, loaded separately)
//!   models/
//!     anthropic.toml           # one file per provider
//!     openai.toml
//!     ...
//! ```

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");

    let models_dir = Path::new(&manifest_dir).join("data/catalog/models");
    let openclaw_dir = Path::new(&manifest_dir).join("data/catalog/openclaw");
    let out_file = Path::new(&out_dir).join("catalog_index.rs");

    println!("cargo:rerun-if-changed=data/catalog/models");
    println!("cargo:rerun-if-changed=data/catalog/openclaw");
    println!("cargo:rerun-if-changed=data/catalog/providers.toml");
    println!("cargo:rerun-if-changed=build.rs");

    let mut entries: Vec<(String, String)> = Vec::new();
    for dir in [&models_dir, &openclaw_dir] {
        if !dir.exists() {
            continue;
        }
        let read = match fs::read_dir(dir) {
            Ok(r) => r,
            Err(e) => {
                panic!("Failed to read {}: {e}", dir.display());
            }
        };
        for entry in read.flatten() {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("toml") {
                continue;
            }
            let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
                continue;
            };
            // The provider-id inside the TOML may differ from the filename
            // (e.g. openclaw/ollama.toml contains models with provider =
            // "ollama-cloud"). We use the filename stem as the include key.
            // The TOML parser later reads the per-entry `provider` field.
            let abs = path
                .canonicalize()
                .unwrap_or_else(|_| path.clone())
                .to_string_lossy()
                .into_owned();
            entries.push((stem.to_string(), abs));
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut body = String::new();
    body.push_str("// AUTO-GENERATED by build.rs. DO NOT EDIT.\n");
    body.push_str("//\n");
    body.push_str("// Lists every TOML file under data/catalog/models/ and\n");
    body.push_str("// data/catalog/openclaw/. Adding a new file there is picked up\n");
    body.push_str("// automatically on the next build.\n");
    body.push_str("//\n");
    body.push_str("// This file is `include!`d by `oxi_ai::catalog::model::models_index()`.\n");
    body.push_str("// It is intentionally written as a body (no `pub fn`) so it can be\n");
    body.push_str("// included inside an existing function.\n\n");
    body.push_str("&[\n");
    for (id, abs) in &entries {
        body.push_str(&format!("    ({id:?}, include_str!(r#\"{abs}\"#)),\n"));
    }
    body.push_str("]\n");

    fs::write(&out_file, body).expect("write OUT_DIR/catalog_index.rs");
}
