#!/usr/bin/env python3
"""Add MIT license / source attribution header to each openclaw TOML file.

Idempotent: re-running is safe. Skips files that already have the header.
"""

import os
import sys
from pathlib import Path

OPENCLAW_DIR = Path("oxi-ai/data/catalog/openclaw")

HEADER_TEMPLATE = """# ----------------------------------------------------------------------------
# Ported from openclaw (MIT) — github.com/openclaw/openclaw
# Original source: extensions/{dir_name}/openclaw.plugin.json
#
# This file's contents are derived from openclaw's `modelCatalog.providers` field
# in the extension manifest. Openclaw is MIT-licensed, compatible with oxi's MIT
# license. Metadata (prices, context windows) may be incomplete or zero-valued in
# the source; verify against vendor docs before relying on these for billing.
#
# Conflicts (same model id in oxi's existing catalog) are resolved in favor of
# the oxi value, which was hand-curated. This file is auto-generated by
# /tmp/port_openclaw.py and SHOULD NOT be edited by hand.
# ----------------------------------------------------------------------------
"""


def has_header(content: str) -> bool:
    return "Ported from openclaw" in content


def main() -> int:
    if not OPENCLAW_DIR.is_dir():
        print(f"Directory not found: {OPENCLAW_DIR}", file=sys.stderr)
        return 1

    total = 0
    skipped = 0
    for path in sorted(OPENCLAW_DIR.glob("*.toml")):
        dir_name = path.stem  # filename stem
        content = path.read_text()
        if has_header(content):
            skipped += 1
            continue
        # Replace the first "# <DisplayName> models" comment line (subagent's
        # header) with our standardized header.
        lines = content.splitlines(keepends=True)
        # Find first line and check if it's a subagent-style comment
        if lines and lines[0].startswith("# ") and "port" in lines[0].lower():
            lines = lines[1:]
        new_content = HEADER_TEMPLATE.format(dir_name=dir_name) + "".join(lines)
        path.write_text(new_content)
        total += 1
        print(f"+ {path}")
    print(f"---")
    print(f"Added: {total}, Skipped (already had): {skipped}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
